# Generated by Django 5.2.3 on 2025-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Farsi')], default='en', max_length=5)),
                ('primary_color', models.CharField(default='#2563eb', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
