# Generated by Django 5.2.4 on 2025-07-12 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
