# Generated by Django 5.2.4 on 2026-08-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_memberships(apps, schema_editor):
    """Create authoritative Membership rows from existing Company/Driver data.

    Owners first, then drivers (get_or_create won't overwrite an owner if a
    user somehow has both profiles).
    """
    Company = apps.get_model('accounts', 'Company')
    Driver = apps.get_model('accounts', 'Driver')
    Membership = apps.get_model('accounts', 'Membership')

    for company in Company.objects.all():
        if company.user_id:
            Membership.objects.get_or_create(
                user_id=company.user_id,
                defaults={'company_id': company.id, 'role': 'COMPANY_OWNER'},
            )

    for driver in Driver.objects.select_related('company').all():
        if driver.user_id and driver.company_id:
            Membership.objects.get_or_create(
                user_id=driver.user_id,
                defaults={'company_id': driver.company_id, 'role': 'DRIVER'},
            )


def noop_reverse(apps, schema_editor):
    # Membership table is dropped by the reverse of CreateModel; nothing to do.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_locationping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COMPANY_OWNER', 'Company Owner'), ('COMPANY_ADMIN', 'Company Admin'), ('DISPATCHER', 'Dispatcher'), ('FLEET_MANAGER', 'Fleet Manager'), ('ACCOUNTANT', 'Accountant'), ('DRIVER', 'Driver')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'role'], name='accounts_me_company_dd3da6_idx')],
            },
        ),
        migrations.RunPython(backfill_memberships, noop_reverse),
    ]
