# Generated by Django 5.2.4 on 2026-08-11 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_driverinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='accounts_dr_company_b8a527_idx'), models.Index(fields=['vehicle', 'is_active'], name='accounts_dr_vehicle_da8c10_idx'), models.Index(fields=['driver', 'is_active'], name='accounts_dr_driver__ef138e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vehicle',), name='uniq_active_vehicle_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('driver',), name='uniq_active_driver_assignment')],
            },
        ),
    ]
