# Generated by Django 5.2.4 on 2026-08-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_trip_created_by_trip_driver_ref_trip_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('cargo_type', models.CharField(blank=True, max_length=64)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='accounts.company')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='accounts.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='accounts_ca_company_606106_idx'), models.Index(fields=['trip'], name='accounts_ca_trip_id_507037_idx')],
            },
        ),
    ]
