# Generated by Django 5.2.4 on 2026-08-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='accounts.trip'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['trip', 'recorded_at'], name='accounts_lo_trip_id_87ac0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationping',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id__isnull', False)), fields=('event_id',), name='uniq_location_event_id'),
        ),
    ]
