# Generated by Django 5.2.4 on 2026-08-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_locationping_event_id_locationping_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='EUR', max_length=8),
        ),
        migrations.AddField(
            model_name='expense',
            name='driver_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.driver'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.trip'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.vehicle'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel', 'Fuel'), ('Maintenance', 'Maintenance'), ('Tolls', 'Tolls'), ('Parking', 'Parking'), ('Insurance', 'Insurance'), ('Salary', 'Salary'), ('Repair', 'Repair'), ('Other', 'Other')], default='Fuel', max_length=16),
        ),
    ]
