# Generated by Django 5.2.4 on 2026-08-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_expense_currency_expense_driver_ref_expense_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('alert_type', models.CharField(choices=[('VEHICLE_OFFLINE', 'Vehicle offline'), ('MAINTENANCE_DUE', 'Maintenance due'), ('LOW_FUEL', 'Low fuel'), ('SPEEDING', 'Excessive speed'), ('GPS_UNAVAILABLE', 'GPS unavailable'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_alerts', to='accounts.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_alerts', to='accounts.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_alerts', to='accounts.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_alerts', to='accounts.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'acknowledged_at'], name='accounts_fl_company_e4e23f_idx'), models.Index(fields=['vehicle', 'alert_type', 'acknowledged_at'], name='accounts_fl_vehicle_e171b6_idx')],
            },
        ),
    ]
