# Generated by Django 5.2.4 on 2026-08-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_fleetalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('distance_unit', models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', max_length=4)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('offline_timeout_seconds', models.PositiveIntegerField(default=120)),
                ('moving_speed_kmh', models.PositiveIntegerField(default=5)),
                ('telemetry_interval_seconds', models.PositiveIntegerField(default=45)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.company')),
            ],
        ),
    ]
