# Generated by Django 5.2.4 on 2026-08-12 09:52

from django.db import migrations, models


def clear_fake_positions(apps, schema_editor):
    """Remove placeholder/stale coordinates.

    Any vehicle that has never reported real telemetry (last_seen_at IS NULL)
    keeps no position at all — this clears the old default 0,0 ("Null Island",
    the ocean marker) and any leftover demo coordinates. Vehicles WITH real
    telemetry are untouched.
    """
    Vehicle = apps.get_model('accounts', 'Vehicle')
    Vehicle.objects.filter(last_seen_at__isnull=True).update(lat=None, lng=None, speed=0)
    # Belt and braces: an exact 0,0 is never a real fleet position.
    Vehicle.objects.filter(lat=0, lng=0).update(lat=None, lng=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_driver_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(clear_fake_positions, noop_reverse),
    ]
