# Generated by Django 5.2.4 on 2026-08-12 12:58

from django.db import migrations, models


def raise_stale_default_timeout(apps, schema_editor):
    """Companies still carrying the old 120s default get the corrected 300s.

    120s was shorter than the real telemetry cadence once Android batches
    fixes, so actively-tracking drivers flapped to OFFLINE. Only rows holding
    the exact old default are touched — a deliberately customised value is
    left alone.
    """
    CompanySettings = apps.get_model('accounts', 'CompanySettings')
    CompanySettings.objects.filter(offline_timeout_seconds=120).update(
        offline_timeout_seconds=300)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_driver_last_seen_at_alter_vehicle_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='offline_timeout_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.RunPython(raise_stale_default_timeout, noop_reverse),
    ]
