# Generated by Django 5.2.4 on 2026-08-13 08:16

from django.db import migrations, models


def collapse_duplicate_alerts(apps, schema_editor):
    """Clean up the duplicates the old de-dup logic produced.

    Acknowledging an alert used to make the de-dup check miss, so every refresh
    recreated the same alert. For each (company, vehicle, alert_type) keep the
    NEWEST occurrence open and mark every older one resolved, so history is
    preserved but the list stops showing repeats.
    """
    FleetAlert = apps.get_model('accounts', 'FleetAlert')
    from django.utils import timezone
    now = timezone.now()
    seen = set()
    for a in FleetAlert.objects.order_by('-created_at').iterator():
        key = (a.company_id, a.vehicle_id, a.alert_type)
        if key in seen:
            if a.resolved_at is None:
                a.resolved_at = now
                a.save(update_fields=['resolved_at'])
        else:
            seen.add(key)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_companysettings_offline_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fleetalert',
            index=models.Index(fields=['company', 'resolved_at'], name='accounts_fl_company_e39478_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetalert',
            index=models.Index(fields=['vehicle', 'alert_type', 'resolved_at'], name='accounts_fl_vehicle_f321ea_idx'),
        ),
        migrations.RunPython(collapse_duplicate_alerts, noop_reverse),
    ]
