# Generated by Django 5.2.4 on 2026-08-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_fleetalert_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'فارسی'), ('de', 'Deutsch'), ('it', 'Italiano')], default='en', max_length=5),
        ),
    ]
