# Generated by Django 5.2.4 on 2026-08-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_expense_approval_expense_liters_expense_odometer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetalert',
            name='alert_type',
            field=models.CharField(choices=[('VEHICLE_OFFLINE', 'Vehicle offline'), ('MAINTENANCE_DUE', 'Maintenance due'), ('LOW_FUEL', 'Low fuel'), ('SPEEDING', 'Excessive speed'), ('GPS_UNAVAILABLE', 'GPS unavailable'), ('INSPECTION_DEFECT', 'Inspection defect'), ('INCIDENT', 'Incident'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
    ]
