# Generated by Django 5.2.4 on 2026-08-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_fleetalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='fuel_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
